blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/nimritagames/Unity-FlowUI/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/nimritagames/Unity-FlowUI#readme
    about: Read the documentation for help and guidance
